version: '2.0'

services:

  haskell:
    build: ./container
    hostname: haskell
    container_name: haskell
    network_mode: host
    volumes:
      - ./home/hs/ghc:/home/hs/.ghc
      - ./home/hs/stack:/home/hs/.stack
      - ./home/hs/local:/home/hs/.local
      - ./Projects:/home/hs/Projects
    privileged: true
    environment:
      - DISPLAY 
    entrypoint: /usr/bin/bash  # /usr/bin/firefox # chromium-browser

