version: '2.0'

services:
  haskell:
    # image: haskell
    build: haskell_container
    hostname: haskell
    container_name: haskell_container
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./Projects:/home/hs/Projects
      - ./haskell_container/ghc:/home/hs/.ghc
      - ./haskell_container/stack:/home/hs/.stack
    stdin_open: true
    tty: true
    command: bash
    network_mode: host
    # restart: always

    
